name: ble
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: 0.6.3+1
  qr_code_scanner: ^0.3.5
  permission_handler: ^10.0.0
  cbor: 3.2.0
  provider: ^4.3.3

flutter:
  uses-material-design: true